// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hanoanjvcxjvptyntpvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhhbm9hbmp2Y3hqdnB0eW50cHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDIzOTEsImV4cCI6MjA3Mjc3ODM5MX0._5kYS0BUmtzxp6soOg6Hlcq7i-24zbQ5j-y99fXoa0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});